import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/app/providers";
import Header from "@/components/common/Header";
import MainNavbar from "@/components/common/MainNavbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="bg-white dark:bg-black" suppressHydrationWarning>
        <Providers>
          <div className="flex flex-col h-screen overflow-hidden">
            <Header />
            <main className="flex items-start flex-1 min-h-0 overflow-hidden">
              <MainNavbar />
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
